### ISSUE TITLE
Building a debian host fails due to network config

### ISSUE THREAD

**Issue by Aftermath** [ryran/upvm#25]
During a pull for debian-8's template, we hit errors regarding non-existent /etc/sysconfig/network-scripts.

```
Enter VMNAME [debian-8] :
  INFO: HOSTNAME not specified; using 'debian-8.example.com'
  INFO: Unable to determine native format of chosen template
  INFO: Using qcow2 for output format (change with --format=raw)
  INFO: Auto-detected os-variant ('debian8') was validated by osinfo-query command
  INFO: Initializing libvirt connection to qemu:///session
  INFO: Starting virt-builder
[   0.7] Downloading: http://libguestfs.org/download/builder/debian-8.xz
[   1.4] Planning how to build this image
[   1.4] Uncompressing
[   5.6] Converting raw to qcow2
[   6.9] Opening the new disk
[  17.6] Setting a random seed
[  17.6] Setting the hostname: debian-8.example.com
[  18.5] Running: echo -e "DHCP_HOSTNAME=debian-8.example.com
DEVICE=eth0" >> /etc/sysconfig/network-scripts/ifcfg-eth0
/bin/sh: 4: cannot create /etc/sysconfig/network-scripts/ifcfg-eth0: Directory nonexistent
virt-builder: error: echo -e "DHCP_HOSTNAME=debian-8.example.com
DEVICE=eth0" >> /etc/sysconfig/network-scripts/ifcfg-eth0: command exited
with an error

If reporting bugs, run virt-builder with debugging enabled and include the
complete output:

  virt-builder -v -x [...]

First execution of 'virt-builder' failed; trying once more ...

[   0.6] Downloading: http://libguestfs.org/download/builder/debian-8.xz
[   1.3] Planning how to build this image
[   1.3] Uncompressing
[   5.7] Converting raw to qcow2
[   6.9] Opening the new disk
[  21.5] Setting a random seed
[  21.5] Setting the hostname: debian-8.example.com
[  22.4] Running: echo -e "DHCP_HOSTNAME=debian-8.example.com
DEVICE=eth0" >> /etc/sysconfig/network-scripts/ifcfg-eth0
/bin/sh: 4: cannot create /etc/sysconfig/network-scripts/ifcfg-eth0: Directory nonexistent
virt-builder: error: echo -e "DHCP_HOSTNAME=debian-8.example.com
DEVICE=eth0" >> /etc/sysconfig/network-scripts/ifcfg-eth0: command exited
with an error

If reporting bugs, run virt-builder with debugging enabled and include the
complete output:

  virt-builder -v -x [...]
virt-builder execution failed; unable to continue
(Please send rsaw@redhat.com this output)

Traceback (most recent call last):
  File "/usr/bin/upvm", line 101, in <module>
    main()
  File "/usr/bin/upvm", line 86, in main
    builder.build()
  File "/usr/share/upvm/modules/builder.py", line 134, in build
    subprocess.check_call(cmd)
  File "/usr/lib64/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['virt-builder', 'debian-8', '--output', '/var/lib/upvm/debian-8.qcow2', '--cache', '/var/cache/upvm', '--hostname', 'debian-8.example.com', '--run-command', 'echo -e "DHCP_HOSTNAME=debian-8.example.com\nDEVICE=eth0" >> /etc/sysconfig/network-scripts/ifcfg-eth0', '--root-password', 'password:redhat', '--format', 'qcow2', '--firstboot', '/tmp/tmp3E7YbZ']' returned non-zero exit status 1
```

**Comment by ryran** [comment]
You rock! Will fix.

**Comment by ryran** [comment]
Fixed in master. Next rpm release will include it.
